# Generated by Django 2.2.5 on 2022-01-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20220129_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='cehck_out',
            new_name='check_out',
        ),
    ]
